# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
CHROMA_OPENAI_API_KEY = "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"
CHROMA_HUGGINGFACE_API_KEY = "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"